name: Build & Release (Native)

on:
    push:
        tags:
            - "v*" # 仅在推 tag 时触发，比如 v1.7.2

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: macos-latest
                      platform: darwin
                      arch: amd64,arm64
                      artifact_name: apple-store-helper-darwin
                    - os: macos-latest
                      platform: windows
                      arch: 386,amd64
                      artifact_name: apple-store-helper-windows

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22"

            - name: Install system dependencies
              run: |
                  # 安装音频开发库（beep 需要）
                  brew install portaudio pkg-config

            - name: Install Fyne tools
              run: |
                  go install fyne.io/fyne/v2/cmd/fyne@latest
                  go install github.com/fyne-io/fyne-cross@latest
                  echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

            - name: Cache fyne-cross engines
              uses: actions/cache@v4
              with:
                  path: ~/.fyne-cross
                  key: ${{ runner.os }}-fyne-cross-${{ matrix.platform }}

            - name: Get tag version
              id: vars
              run: echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

            - name: Setup fyne-cross engine
              run: fyne-cross setup ${{ matrix.platform }}

            - name: Build with fyne-cross
              run: |
                  export PATH="$(go env GOPATH)/bin:$PATH"
                  fyne-cross ${{ matrix.platform }} \
                    -arch=${{ matrix.arch }} \
                    -app-id=apple.store.helper \
                    -name="Apple Store Helper" \
                    -ldflags="-X 'github.com/hteen/apple-store-helper/common.VERSION=${{ steps.vars.outputs.tag }}'"

                  if [ ! -d "fyne-cross/dist" ]; then
                      echo "❌ fyne-cross 构建失败：dist 目录未生成"
                      exit 1
                  fi
                  echo "✅ fyne-cross 构建成功"

            - name: Fix quarantine & codesign (Darwin)
              if: matrix.platform == 'darwin'
              run: |
                  for arch in ${{ matrix.arch }}; do
                      app_path="fyne-cross/dist/darwin-${arch}/Apple Store Helper.app"
                      if [ -d "$app_path" ]; then
                          echo "Fixing quarantine and signing $app_path"
                          xattr -cr "$app_path"
                          codesign --force --deep --sign - "$app_path"
                          echo "✅ $arch 版本签名完成"
                      else
                          echo "⚠️ $arch 版本应用包未找到"
                      fi
                  done

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.artifact_name }}-${{ steps.vars.outputs.tag }}
                  path: fyne-cross/dist/
                  if-no-files-found: error
                  retention-days: 30

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: ./artifacts

            - name: Release
              uses: ncipollo/release-action@v1
              with:
                  tag: ${{ github.ref_name }}
                  name: Release ${{ github.ref_name }}
                  body: |
                      ## What's New
                      - Auto build for ${{ github.ref_name }}
                      - Cross-platform build with fyne-cross
                      - Supports: darwin-amd64, darwin-arm64, windows-386, windows-amd64
                  artifacts: "artifacts/*"
